### ISSUE TITLE
managing dotfiles fails unless home_perms_recursive: true and if setting that ends up changing pers of everything inside the homefolder to 0755

### ISSUE THREAD

**Issue by ingardm** [vshn/puppet-identity#3]
the module wont copy any dotfiles unless recursing is enabled and while the pers mode is set to 0755 for the home dir it will apply the same permissions to every file inside the homedir

**Comment by tobru** [comment]
Thanks for reporting this issue. Will have a look into it as soon as I have time

**Comment by ingardm** [comment]
setting perms to undef instead of the default 0755 fixes it, but then you
wont be able to set the permissions on the home folder either

2015-11-20 13:48 GMT+01:00 Tobias Brunner notifications@github.com:

> Thanks for reporting this issue. Will have a look into it as soon as I
> have time
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vshn/puppet-identity/issues/3#issuecomment-158389318.

## 

Ingard Mevåg
Driftssjef
JottaCloud

Mobil: +47 450 22 834
E-post: ingard@jottacloud.com
Webside: www.jottacloud.com
